<!-- Copyright 2026 上海如静知华信息科技有限公司 -->
<script setup>import AdminShell from '../../components/AdminShell.vue';import StatusBadge from '../../components/StatusBadge.vue';import {receivables,payables,cashflow,budgets} from '../../api/mock';const profit=[64,78,70,86,77,93,82,98,84,100,89,96]</script>
<template><AdminShell><template #title>经营分析驾驶舱</template>
  <div class="page-heading"><div><p>EXECUTIVE INSIGHTS</p><h1>经营分析驾驶舱</h1><span>销售、供应链、财务、制造与交付的统一经营视图</span></div><div><button class="button secondary">订阅月报</button><button class="button primary">＋ 新建分析</button></div></div>
  <section class="metric-grid five"><article><header><span>年度营业收入</span><i>￥</i></header><strong>4,250<small> 万</small></strong><p><b>↑ 8.6%</b> 同比增长</p></article><article><header><span>加权销售漏斗</span><i>销</i></header><strong>1,994<small> 万</small></strong><p>高意向商机 23 个</p></article><article><header><span>在执行项目</span><i>项</i></header><strong>33<small> 个</small></strong><p>3 个项目存在风险</p></article><article><header><span>年度目标完成率</span><i>标</i></header><strong>78.4<small> %</small></strong><p>领先时间进度 2.1%</p></article><article class="warning"><header><span>指标预警</span><i>!</i></header><strong>4<small> 项</small></strong><p><b>1 项</b> 为交付红色预警</p></article></section>
  <section class="dashboard-grid"><div class="card cash-trend"><header><div><h2>收入与毛利趋势</h2><p>近 12 个月营业收入和毛利额</p></div><div class="legend"><span><i></i>营业收入</span><span><i></i>毛利额</span></div></header><div class="chart-area"><div class="chart-scale"><span>240</span><span>180</span><span>120</span><span>60</span><span>0</span></div><div class="bar-chart"><div v-for="(v,i) in cashflow" :key="i" class="bar-group"><div><i :style="{height:v/2.3+'px'}"></i><em :style="{height:profit[i]/2.3+'px'}"></em></div><small>{{i+1}}月</small></div></div></div><footer><div><span>累计营业收入</span><b>4,250 万</b></div><div><span>累计营业成本</span><b>2,786 万</b></div><div><span>综合毛利率</span><b class="positive">34.4%</b></div></footer></div>
  <div class="card action-center"><header><div><h2>数据刷新与预警</h2><p>按业务影响和执行时间排序</p></div><em>数据任务 →</em></header><article v-for="(x,i) in payables" :key="x.no"><time>{{['02:15','03:20','15min','08:00'][i]}}</time><i :class="['dot',i===2?'amber':'teal']"></i><div><b>{{x.supplier}}</b><small>{{x.source}} · {{x.amount}} 万行</small></div><StatusBadge :value="x.status"/></article><footer>今日数据任务成功率 <b>99.2%</b></footer></div></section>
  <section class="dashboard-bottom"><div class="card"><header><div><h2>核心经营指标</h2><p>目标值、当前值与责任人</p></div><em>指标中心 →</em></header><table><thead><tr><th>指标 / 口径</th><th>统计日期</th><th>目标差异</th><th>状态</th></tr></thead><tbody><tr v-for="x in receivables.slice(0,4)" :key="x.no"><td><b>{{x.customer}}</b><small>{{x.no}} · {{x.source}}</small></td><td>{{x.due}}</td><td><b>{{(x.received-x.amount).toFixed(1)}}</b></td><td><StatusBadge :value="x.status"/></td></tr></tbody></table></div>
  <div class="card budget-brief"><header><div><h2>主题域覆盖</h2><p>关键指标资产建设进度</p></div><em>数据地图 →</em></header><article v-for="x in budgets.slice(0,4)" :key="x.dept"><div><b>{{x.dept}}</b><small>{{x.subject}} · {{x.actual}} / {{x.annual}} 项</small></div><strong>{{x.rate}}%</strong><span><i :class="{warn:x.status==='预警'}" :style="{width:x.rate+'%'}"></i></span></article></div>
  <div class="card"><header><div><h2>管理报表订阅</h2><p>自动生成并定时推送</p></div><em>订阅中心 →</em></header><div class="payment-list"><article v-for="(x,i) in payables" :key="x.no"><time><b>{{['周','月','日','季'][i]}}</b><small>频率</small></time><div><b>{{x.supplier.replace('同步','分析简报')}}</b><small>{{x.source}}</small></div><strong>{{x.status}}</strong></article></div></div></section>
</AdminShell></template>
