-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/
CREATE TABLE sys_user (id BIGINT PRIMARY KEY AUTO_INCREMENT,username VARCHAR(40) NOT NULL UNIQUE,password VARCHAR(100) NOT NULL,display_name VARCHAR(40) NOT NULL,role VARCHAR(20) NOT NULL,enabled BOOLEAN NOT NULL DEFAULT TRUE,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE bi_data_source (id BIGINT PRIMARY KEY AUTO_INCREMENT,account_code VARCHAR(32) NOT NULL UNIQUE,account_name VARCHAR(80) NOT NULL,bank_name VARCHAR(80) NOT NULL,account_type VARCHAR(40) NOT NULL,balance DECIMAL(16,2) NOT NULL,available_balance DECIMAL(16,2) NOT NULL,currency VARCHAR(16) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE bi_business_metric (id BIGINT PRIMARY KEY AUTO_INCREMENT,business_metric_no VARCHAR(32) NOT NULL UNIQUE,customer_name VARCHAR(100) NOT NULL,source_document VARCHAR(100) NOT NULL,amount DECIMAL(16,2) NOT NULL,received_amount DECIMAL(16,2) NOT NULL,due_date DATE NOT NULL,owner VARCHAR(40) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE bi_data_job (id BIGINT PRIMARY KEY AUTO_INCREMENT,data_job_no VARCHAR(32) NOT NULL UNIQUE,supplier_name VARCHAR(100) NOT NULL,source_document VARCHAR(100) NOT NULL,amount DECIMAL(16,2) NOT NULL,paid_amount DECIMAL(16,2) NOT NULL,due_date DATE NOT NULL,applicant VARCHAR(40) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE bi_analysis_workbook (id BIGINT PRIMARY KEY AUTO_INCREMENT,claim_no VARCHAR(32) NOT NULL UNIQUE,claimant VARCHAR(40) NOT NULL,department VARCHAR(60) NOT NULL,category VARCHAR(40) NOT NULL,purpose VARCHAR(160) NOT NULL,amount DECIMAL(14,2) NOT NULL,expense_date DATE NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE TABLE bi_subject_area (id BIGINT PRIMARY KEY AUTO_INCREMENT,subject_area_no VARCHAR(32) NOT NULL UNIQUE,department VARCHAR(60) NOT NULL,subject_name VARCHAR(60) NOT NULL,fiscal_year INT NOT NULL,annual_amount DECIMAL(16,2) NOT NULL,occupied_amount DECIMAL(16,2) NOT NULL,actual_amount DECIMAL(16,2) NOT NULL,status VARCHAR(20) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL);
CREATE INDEX idx_bi_business_metric_due ON bi_business_metric(due_date,status);
CREATE INDEX idx_bi_data_job_due ON bi_data_job(due_date,status);
CREATE INDEX idx_bi_expense_status ON bi_analysis_workbook(status,expense_date);
CREATE INDEX idx_bi_subject_area_year_dept ON bi_subject_area(fiscal_year,department);
